# Makefile
#essentially does g++ -Wno-deprecated board.cc ghost.cc player.cc main.cc myrandom.cc randplayer.cc -o game

CC = g++

FLAGS = -Wno-deprecated
PROG = game

game:
	$(CC) -g $(INCLUDE) board.cc ghost.cc player.cc myrandom.cc adamplayer.cc randplayer.cc main.cc $(FLAGS) -o $(PROG)

